# CSCI4022 Homework 2; Review

## Due Monday, February 8 at 11:59 pm to Canvas

#### Submit this file as a .ipynb with *all cells compiled and run* to the associated dropbox.

***

Your solutions to computational questions should include any specified Python code and results as well as written commentary on your conclusions.  Remember that you are encouraged to discuss the problems with your classmates, but **you must write all code and solutions on your own**.

**NOTES**: 

- Any relevant data sets should be available on Canvas. To make life easier on the graders if they need to run your code, do not change the relative path names here. Instead, move the files around on your computer.
- If you're not familiar with typesetting math directly into Markdown then by all means, do your work on paper first and then typeset it later.  Here is a [reference guide](https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference) linked on Canvas on writing math in Markdown. **All** of your written commentary, justifications and mathematical work should be in Markdown.  I also recommend the [wikibook](https://en.wikibooks.org/wiki/LaTeX) for LaTex.
- Because you can technically evaluate notebook cells is a non-linear order, it's a good idea to do **Kernel $\rightarrow$ Restart & Run All** as a check before submitting your solutions.  That way if we need to run your code you will know that it will work as expected. 
- It is **bad form** to make your reader interpret numerical output from your code.  If a question asks you to compute some value from the data you should show your code output **AND** write a summary of the results in Markdown directly below your code. 
- 45 points of this assignment are in problems.  The remaining 5 are for neatness, style, and overall exposition of both code and text.
- This probably goes without saying, but... For any question that asks you to calculate something, you **must show all work and justify your answers to receive credit**. Sparse or nonexistent work will receive sparse or nonexistent credit. 
- There is *not a prescribed API* for these problems.  You may answer coding questions with whatever syntax or object typing you deem fit.  Your evaluation will primarily live in the clarity of how well you present your final results, so don't skip over any interpretations!  Your code should still be commented and readable to ensure you followed the given course algorithm.

---

In [34]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import random
import seaborn as sns
import re

***
<a/ id='p1'></a>
[Back to top](#top)
# Problem 1 (Theory: minhashing; 10 pts)

Consider minhash values for a single column vector that contains 10 components/rows. Seven of rows hold 0 and three hold 1. Consider taking all 10! = 3,628,800 possible distinct permutations of ten rows. When we choose a permutation of the rows and produce a minhash value for the column, we will use the number of the row, in the permuted order, that is the first with a 1.  Use Markdown cells to demonstrate answers to the following.

#### a) For exactly how many of the 3,628,800 permutations is the minhash value for the column a 9?  What proportion is this?

None. Because in the worst case we have all seven 0 first (in the 1-7 digits), so the 8th digit will be a 1 making it impposible for 9 to be the value. 

#### b) For exactly how many of the 3,628,800 permutations is the minhash value for the column a 8?

This happens when all first seven digits are 0. any of the seven 0 can take digit 1, and any of the seven 0 can take on digit two and so on... so 7^7 = 823543

#### c) For exactly how many of the 3,628,800 permutations is the minhash value for the column a 3?

This happens when first two digits are 0 and the third is a 1. 

***
<a/ id='p3'></a>
[Back to top](#top)
# Problem 2 (Applied Minhashing; 35 pts)

In this problem we compare similarities of 5 documents available on http://www.gutenberg.org

 1) The first approximately 10000 characters of Miguel de Unamuno's *Niebla*, written in Spanish, in the file `niebla.txt`
 
 2) The first approximately 10000 characters of Miguel de Cervantes *The Ingenious Gentleman Don Quixote of La Mancha*, written in Spanish, in the file `DQ.txt`
 
 3) The first approximately 10000 characters of Homer's *The Odyssey*, translated into English by Samuel Butler, in the file `odyssey.txt`
 
 4) The first approximately 10000 characters of Kate Chopin's *The Awakening* in the file `awaken.txt`
 
 5) The entirety of around 12000 characters of Kate Chopin's *Beyond the Bayou* in the file `BB.txt`
 
### a) Clean the 4 documents, scrubbing all punctuation, changes cases to lower case, and removing accent marks as appropriate.  

You should have only 27 unique characters in each book/section after cleaning, corresponding to white spaces and the 26 letters.  


**For this problem, you may import any text-based packages you desire to help wrangle the data.**  I recommend looking at some functions within `string` or the RegEx `re` packages.

You can and probably should use functions in the string package such as `string.lower`, `string.replace`, etc.

All 5 documents have been saved in UTF-8 encoding.




In [35]:
dfR_ody = pd.read_fwf('/users/tamer/desktop/advanced_ds/data/odyssey.txt',names = ['odyssey'])
dfR_niebla = pd.read_fwf('/users/tamer/desktop/advanced_ds/data/niebla.txt',names = ['niebla'])
dfR_DQ = pd.read_fwf('/users/tamer/desktop/advanced_ds/data/DQ.txt',names = ['DQ'])
dfR_awaken = pd.read_fwf('/users/tamer/desktop/advanced_ds/data/awaken.txt',names = ['awaken'])
dfR_BB = pd.read_fwf('/users/tamer/desktop/advanced_ds/data/BB.txt',names = ['BB'])


In [36]:
#not proud of this implementation, but it works. Here after I cleaned my data then I converted my data frames into lists
niebla,dq,odyssey,awaken,bb = [],[],[],[],[]
dfR_niebla['niebla'] = dfR_niebla['niebla'].replace('[^a-z A-Z]','',regex=True)
dfR_DQ['DQ'] = dfR_DQ['DQ'].replace('[^a-z A-Z]','',regex=True)
dfR_ody['odyssey'] = dfR_ody['odyssey'].replace('[^a-z A-Z]','',regex=True)
dfR_awaken['awaken'] = dfR_awaken['awaken'].replace('[^a-z A-Z]','',regex=True)
dfR_BB['BB'] = dfR_BB['BB'].replace('[^a-z A-Z]','',regex=True)

for i in dfR_niebla['niebla']:
    niebla.append(i.lower())
    
for i in dfR_DQ['DQ']:
    dq.append(i.lower())
    
for i in dfR_ody['odyssey']:
    odyssey.append(i.lower())
    
for i in dfR_awaken['awaken']:
    awaken.append(i.lower())
    
for i in dfR_BB['BB']:
    bb.append(i.lower())



### b) Compute exact similarity scores between the documents.  Are these the expected results?

Notes:
- You may choose or explore different values of $k$ for your shingles.
- You may choose to shingle on words and create an n-gram model, but it is recommended you shingle on letters as described in class
- You may construct your characteristic matrix or characteristic sets with or without hash functions (e.g. by using `set()`).  Note that choice of hash function should change heavily with $k$!

In [37]:
# merge list elements into one element found at https://stackoverflow.com/questions/12453580/how-to-concatenate-items-in-a-list-to-a-single-string

# initilize 5 sets to hold shingles.
shingles_niebla,shingles_dq,shingles_odyssey,shingles_awaken,shingles_bb =set(),set(),set(),set(),set()

#initilize 5 strings to hold the 5 documents
niebla_string, dq_string, odyssey_string, awaken_string, bb_string = "","","","",""

# convert documents to one huge string
niebla_string, dq_string, odyssey_string, awaken_string, bb_string=' '.join(niebla) ,' '.join(dq) ,' '.join(odyssey),' '.join(awaken),' '.join(bb)  

#sizes of each of the documents (used in each of the documents loops)
niebla_size, dq_size, odyssey_size, awaken_size, bb_size =len(niebla_string) ,len(dq_string) ,len(odyssey_string),len(awaken_string),len(bb_string)   

k = 4 # number of shingles we choose (letters)

# here we shingle(length k). I will do 5 loops, one for each of the documents( ugly but works just fine)


start = 0 # we start at 0
end = k # marking the end of a shingle
while start < niebla_size:
    
    shingles_niebla.add(niebla_string[start:end]) 
    start = start + k 
    end = end + k
    

start = 0 # we start at 0
end = k # marking the end of a shingle
while start < dq_size:
    
    shingles_dq.add(dq_string[start:end]) 
    start = start + k 
    end = end + k    

    
start = 0 # we start at 0
end = k # marking the end of a shingle
while start < odyssey_size:
    
    shingles_odyssey.add(odyssey_string[start:end]) 
    start = start + k 
    end = end + k
    
    
start = 0 # we start at 0
end = k # marking the end of a shingle
while start < awaken_size:
    
    shingles_awaken.add(awaken_string[start:end]) 
    start = start + k 
    end = end + k
    
    
    
start = 0 # we start at 0
end = k # marking the end of a shingle
while start < bb_size:
    
    shingles_bb.add(bb_string[start:end]) 
    start = start + k 
    end = end + k
  

name = ['niebla','dq','odyssey','awaken','bb'] 
shingles = [shingles_niebla,shingles_dq,shingles_odyssey,shingles_awaken,shingles_bb]
for j in range(5):
    for i in range(5):
    
        print(name[j] ,"similarity to", name[i],"=", len(shingles[j].intersection(shingles[i]))/len(shingles[j].union(shingles[i])))
    print("-----------------------------------------")


niebla similarity to niebla = 1.0
niebla similarity to dq = 0.1641156462585034
niebla similarity to odyssey = 0.047635021804763505
niebla similarity to awaken = 0.04577822990844354
niebla similarity to bb = 0.04528061224489796
-----------------------------------------
dq similarity to niebla = 0.1641156462585034
dq similarity to dq = 1.0
dq similarity to odyssey = 0.03971789161098738
dq similarity to awaken = 0.041085563513004145
dq similarity to bb = 0.04526166902404526
-----------------------------------------
odyssey similarity to niebla = 0.047635021804763505
odyssey similarity to dq = 0.03971789161098738
odyssey similarity to odyssey = 1.0
odyssey similarity to awaken = 0.1897920604914934
odyssey similarity to bb = 0.1944941008223096
-----------------------------------------
awaken similarity to niebla = 0.04577822990844354
awaken similarity to dq = 0.041085563513004145
awaken similarity to odyssey = 0.1897920604914934
awaken similarity to awaken = 1.0
awaken similarity to bb = 0.

This is showing that niebla and bq are similar. And oddyssey,bb nd awaken are similar. This is expected since niebla and bq are both in spanish while the others are in english.


### c) Implement minhashing with 1000 hash functions on the 4 documents, checking your results against those in part b).

- You may choose your own value of $p$ as the modulus of the hash functions.  You are encouraged to use the example code from the minhashing in class notebook to start you out.

In [38]:
#here im trying to construct a charactristic matrix from the emplementation above,
#so i can feed it directly to my borrowed min hash function

#"everything" holds the union of all shingles(non repeating)
everything = shingles_niebla.union(shingles_dq) 
everything = everything.union(shingles_odyssey)
everything = everything.union(shingles_awaken)
everything = everything.union(shingles_bb)

niebla,dq,odyssey,awaken,bb = [],[],[],[],[]
everything = pd.DataFrame(everything,columns= ['index'])
#loop over all shingles(evertything) and ask if it is in each of the 'shingles' constructed above,
#then we merge al of them together into one df called char_mat
for i in everything['index']:
    
    if i in shingles_niebla:
        niebla.append(1)
    else:
        niebla.append(0)
        
    if i in shingles_dq:
        dq.append(1)
    else:
        dq.append(0)
        
    if i in shingles_odyssey:
        odyssey.append(1)
    else:
        odyssey.append(0)
        
    if i in shingles_awaken:
        awaken.append(1)
    else:
        awaken.append(0)
        
    if i in shingles_bb:
        bb.append(1)
    else:
        bb.append(0)
    
char_mat = pd.DataFrame({'niebla':niebla,'dq':dq,'odyssey':odyssey,'awaken':awaken,'bb':bb},columns=name)

print(char_mat)

      niebla  dq  odyssey  awaken  bb
0          1   0        0       0   0
1          0   0        1       0   0
2          1   0        0       0   0
3          0   0        1       0   0
4          1   1        0       1   0
...      ...  ..      ...     ...  ..
5546       0   0        1       0   1
5547       0   0        0       0   1
5548       1   0        0       0   0
5549       0   0        1       1   0
5550       0   0        0       1   1

[5551 rows x 5 columns]


In [39]:
#source: notebooks
#feed above char matrix to minhash with 1000 hash functions. we have around 5.5k rows so we need a prime(Phash) larger than that

def minhash(nhash, dfC):
    '''
    Takes a number of hash functions to use (nhash) and characteristic matrix (dfC)
    '''
    # use the "universal hash":  (a*x+b) mod p, where a, b are random ints and p > N (= 10 here) is prime
    np.random.seed(4022)
    Ahash = np.random.choice(range(0,10000), size=nhash)
    Bhash = np.random.choice(range(0,10000), size=nhash)
    Phash =   5701  #prime bigger than 5551

    # STEP 2:  initialize signature matrix to all infinities

    # initialize the signature matrix
    Msig = np.full([nhash, len(dfC.columns)], fill_value=np.inf)

    # fill in the signature matrix:

    # For each row of the characteristic matrix... 
    hash_vals = [0]*nhash # initialize
    for r in range(len(dfC)):
        # STEP 3:  Compute hash values (~permuted row numbers) for that row under each hash function
        for h in range(nhash):
            hash_vals[h] = (Ahash[h]*r + Bhash[h])%Phash
        # STEP 4:  For each column, if there is a 0, do nothing...
        for c in range(len(dfC.columns)):
            # ... but if there is a 1, replace signature matrix element in that column for each hash fcn 
            # with the minimum of the hash value in this row, and the current signature matrix element
            if dfC.iloc[r,c]==1:
                for h in range(nhash):
                    if hash_vals[h] < Msig[h,c]:
                        Msig[h,c] = hash_vals[h]
    return Msig



In [40]:
m_sig = minhash(1000,char_mat)
print(m_sig)

[[ 0.  0. 10.  7.  1.]
 [ 0.  2.  1.  5.  4.]
 [ 1.  1.  0.  0.  0.]
 ...
 [ 0.  1.  2.  1.  7.]
 [ 4.  1.  0.  3.  0.]
 [ 1.  4.  0.  3.  2.]]


In [41]:
for i in range(5):
    for j in range(5):
        
        print(name[i],"similarity to",name[j],"=",sum(m_sig[:,i]==m_sig[:,j])/1000)
    print("-----------------------")

niebla similarity to niebla = 1.0
niebla similarity to dq = 0.175
niebla similarity to odyssey = 0.049
niebla similarity to awaken = 0.057
niebla similarity to bb = 0.043
-----------------------
dq similarity to niebla = 0.175
dq similarity to dq = 1.0
dq similarity to odyssey = 0.035
dq similarity to awaken = 0.034
dq similarity to bb = 0.038
-----------------------
odyssey similarity to niebla = 0.049
odyssey similarity to dq = 0.035
odyssey similarity to odyssey = 1.0
odyssey similarity to awaken = 0.196
odyssey similarity to bb = 0.221
-----------------------
awaken similarity to niebla = 0.057
awaken similarity to dq = 0.034
awaken similarity to odyssey = 0.196
awaken similarity to awaken = 1.0
awaken similarity to bb = 0.214
-----------------------
bb similarity to niebla = 0.043
bb similarity to dq = 0.038
bb similarity to odyssey = 0.221
bb similarity to awaken = 0.214
bb similarity to bb = 1.0
-----------------------


### d) Discussion:

Can we detect expected differences here?  Are the two Spanish docuemnts most similar to each other?  Are the two documents by the same author, with the same theme, the most similar?  What kind of alternatives might have captured the structures between these texts?



The minhash solution looks pretty much like the exact calculation soltuion. I can see that the two Spanish documents are more similar to each other than they are to the english documents, since their similarity scores are in the tenth decimal point while the other are in the thousands decimal point. following the same proccess, I can see that the English documents are more similar to each other than the Spanish documents. The two documents with the same author don't seem more similar to each other than the third (good author?). One good alternative would be author's age. Example: two authors could have more similar writing if they are in the same agr group. 